name: CD
on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  create-version-pr-or-release:
    runs-on: ubuntu-latest
    outputs:
      should-deploy: ${{ steps.changesets.outputs.published == 'true' }}
      update-pom-version: ${{ steps.changesets.outputs.hasChangesets == 'true' && steps.changesets.outputs.published == 'false'  }}
      release-version: "${{ steps.get-version.outputs.version }}"

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.1

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install Node Dependencies
        run: npm ci

      - name: Create Version PR or Github Release
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npx changeset tag
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGESETS_TOKEN }}

      - name: Echo outputs of changesets
        run: echo '${{ toJson(steps.changesets.outputs) }}'

      - name: Set Release Version
        if: steps.changesets.outputs.published == 'true'
        id: get-version
        run: echo "version=${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}" >> $GITHUB_OUTPUT

      - name: Echo outputs of get-version
        if: steps.changesets.outputs.published == 'true'
        run: echo '${{ toJson(steps.get-version.outputs) }}'

  update-pom-version:
    needs: create-version-pr-or-release
    if: needs.create-version-pr-or-release.outputs.update-pom-version == 'true'
    uses: ./.github/workflows/Update-Pom-Versions-of-Release.yaml
    secrets: inherit
    with:
      changeset-branch: "changeset-release/main"

  run-tests-on-release:
    needs: create-version-pr-or-release
    if: needs.create-version-pr-or-release.outputs.should-deploy == 'true'
    uses: ./.github/workflows/Test.yaml
    secrets: inherit

  push-to-repo:
    needs: [run-tests-on-release, create-version-pr-or-release]
    uses: ./.github/workflows/Push-Plugin-to-Release.yaml
    secrets: inherit
    with:
      release-version: ${{ needs.create-version-pr-or-release.outputs.release-version }}

  deploy-to-central:
    needs: [run-tests-on-release, create-version-pr-or-release]
    uses: ./.github/workflows/Deploy-to-Central.yaml
    secrets: inherit
    with:
      release-version: ${{ needs.create-version-pr-or-release.outputs.release-version }}