name: Test
on:
  workflow_call:

jobs:
  test-and-build:
    runs-on: self-hosted

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.1

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean test
